[General]
codepage=65001
AutoKeyboardSwitching=F
DialogFontsize=12
LowerCaseLetters=aábcdeéfghiíjklmnñoópqrstuúüvwxyz
NoCaseLetters='
RTL=F
UpperCaseLetters=AÁBCDEÉFGHIÍJKLMNÑOÓPQRSTUÚÜVWXYZ
errors=
font=Charis SIL AmArea
name=Nahuatl
separator=/
size=12

[Checking]

[Characters]
Chr01=a/A á/Á
Chr02=b/B
Chr03=c/C
Chr04=ch
Chr05=d/D
Chr06=e/E é/É
Chr07=f/F
Chr08=g/G
Chr09=h/H
Chr10=i/I í/Í
Chr11=j/J
Chr12=k/K kw
Chr13=kw
Chr14=l/L
Chr15=ll
Chr16=m/M
Chr17=n/N
Chr18=ñ/Ñ
Chr19=o/O ó/Ó
Chr20=p/P
Chr21=q/Q
Chr22=r/R
Chr23=s/S
Chr24=sh
Chr25=t/T
Chr26=ts
Chr27=u/U ú/Ú ü/Ü
Chr28=v/V
Chr29=w/W
Chr30=x/X
Chr31=y/Y
Chr32=z/Z
Chr33='

[Punctuation]
diacritics=
diacriticsfollow=No
footnotes=
medial=-
