/**
 * Copyright (c) 2020 SIL International
 * This software is licensed under the LGPL, version 2.1 or later
 * (http://www.gnu.org/licenses/lgpl-2.1.html)
 */
package org.sil.syllableparser.service.filter;

/**
 * @author Andy Black
 *
 */
public enum WordsFilterType {
	CV_CORRECT,
	CV_PREDICTED,
	CV_WORDS,
	CV_WORDS_PREDICTED_VS_CORRECT,
	MORAIC_CORRECT,
	MORAIC_PREDICTED,
	MORAIC_WORDS,
	MORAIC_WORDS_PREDICTED_VS_CORRECT,
	NUCLEAR_PROJECTION_CORRECT,
	NUCLEAR_PROJECTION_PREDICTED,
	NUCLEAR_PROJECTION_WORDS,
	NUCLEAR_PROJECTION_WORDS_PREDICTED_VS_CORRECT,
	ONC_CORRECT,
	ONC_PREDICTED,
	ONC_WORDS,
	ONC_WORDS_PREDICTED_VS_CORRECT,
	OT_CORRECT,
	OT_PREDICTED,
	OT_WORDS,
	OT_WORDS_PREDICTED_VS_CORRECT,
	SH_CORRECT,
	SH_PREDICTED,
	SH_WORDS,
	SH_WORDS_PREDICTED_VS_CORRECT,
}
